import '../globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const figtree = Figtree({subsets: ['latin', 'latin-ext']})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "cz" }];
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: { lang : string}
}) {
  return (
    <html lang={params.lang}>
      <body className={figtree.className}>{children}</body>
    </html>
  );
}
